# Generated by Django 6.0.2 on 2026-02-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnos',
            options={'ordering': ['-creacion'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='created',
            new_name='actualizacion',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='updated',
            new_name='creacion',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Fotos', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(max_length=12, verbose_name='Matricula'),
        ),
    ]
