# Generated by Django 6.0.1 on 2026-02-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_conmentario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conmentario',
            new_name='Comentario',
        ),
    ]
